ALTER SESSION SET CONTAINER = MPSS;

CREATE TABLESPACE GIT_API DATAFILE 'git_api.dbf' SIZE 10M AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE USER GITAPITASK_APP IDENTIFIED BY pass DEFAULT TABLESPACE GIT_API QUOTA UNLIMITED ON GIT_API;

GRANT CONNECT, RESOURCE, DBA TO GITAPITASK_APP;